steps:
  - group: ':baby::skin-tone-5: Early Education'
    steps:
      - label: 'High School'
        key: 'high-school'
        command: scripts/study.sh
        artifact_paths: ./education-*.md
        env:
          COURSE_NAME: 'High School'
          FROM: '2007-01'
          TO: '2009-12'
      - label: 'Microsoft Students To Business'
        command: scripts/study.sh
        artifact_paths: ./education-*.md
        env:
          COURSE_NAME: 'Microsoft Students To Business'
          FROM: '2009'
          TO: '2009'
      - label: 'Certified Computer Systems Analyst'
        command: scripts/study.sh
        artifact_paths: ./education-*.md
        env:
          COURSE_NAME: 'Certified Computer Systems Analyst'
          FROM: '2008'
          TO: '2010'

  - wait: ~

  - group: ':adult::skin-tone-5: College Years'
    steps:
      - label: 'Information Technology for Business'
        command: scripts/study.sh
        depends_on: 'high-school'
        artifact_paths: ./education-*.md
        env:
          COURSE_NAME: 'Information Technology for Business'
          FROM: '2010'
          TO: '2012'
      - label: 'Software Engineer at MCOM'
        key: 'mcom'
        command: scripts/work.sh
        artifact_paths: ./experience-*.md
        env:
          JOB_TITLE: 'Software Engineer'
          COMPANY: 'MCOM'
          SKILLS: 'C#, ASP.NET MVP, SQL Server, Entity Framework'
          FROM: '2010-08'
          TO: '2012-08'

  - wait: ~

  - group: ':male_mage::skin-tone-5: Professional Experience'
    steps:
      - label: 'Software Engineer at Lambda3'
        key: 'lambda3'
        depends_on: 'mcom'
        command: scripts/work.sh
        artifact_paths: ./experience-*.md
        env:
          JOB_TITLE: 'Software Engineer'
          COMPANY: 'Lambda3'
          SKILLS: 'Ruby, JavaScript, C#, Sinatra, MonoRail, ASP.NET WebAPI'
          FROM: '2012-08'
          TO: '2014-04'
      - label: 'Software Engineer at Springboard Retail'
        key: 'software-engineer-springboard-retail'
        depends_on: 'lambda3'
        command: scripts/work.sh
        artifact_paths: ./experience-*.md
        env:
          JOB_TITLE: 'Software Engineer Developer'
          COMPANY: 'Springboard Retail'
          SKILLS: 'Ruby, Go, Sinatra, PostgreSQL, React, Buildkite'
          FROM: '2014-04'
          TO: '2015-09'
      - label: 'Lead Developer at Springboard Retail'
        key: 'lead-developer-springboard-retail'
        depends_on: 'software-engineer-springboard-retail'
        command: scripts/work.sh
        artifact_paths: ./experience-*.md
        env:
          JOB_TITLE: 'Lead Developer'
          COMPANY: 'Springboard Retail'
          SKILLS: 'Ruby, Go, Sinatra, PostgreSQL, React, Buildkite, IaC, k8s, Leadership, Hiring'
          FROM: '2015-09'
          TO: '2020-03'
      - label: 'Lead Developer at Heartland (A Global Payments Company)'
        key: 'heartland'
        depends_on: 'lead-developer-springboard-retail'
        command: scripts/work.sh
        artifact_paths: ./experience-*.md
        env:
          JOB_TITLE: 'Lead Developer'
          COMPANY: 'Heartland (A Global Payments Company)'
          SKILLS: 'Ruby, Go, Sinatra, PostgreSQL, React, Buildkite, IaC, k8s, Leadership, Hiring'
          FROM: '2020-03'
          TO: '2022-11'
      - label: 'Senior Software Engineer at BiggerPockets'
        key: 'biggerpockets'
        depends_on: 'heartland'
        command: scripts/work.sh
        artifact_paths: ./experience-*.md
        env:
          JOB_TITLE: 'Senior Software Engineer'
          COMPANY: 'BiggerPockets'
          SKILLS: 'Ruby on Rails, ViewComponents, PostgreSQL, CircleCI, Heroku'
          FROM: '2022-11'
          TO: 'Present'
      - label: 'Senior Engineer (Pipelines) at Buildkite'
        depends_on: biggerpockets
        command: |
          echo "Work In Progress"
          exit 75
        soft_fail:
          - exit_status: 75

  - wait:
    continue_on_failure: true

  - label: ':memo: Build & Publish Resume'
    command: |
      scripts/build-resume.sh
      cat resume.md | buildkite-agent annotate
    artifact_paths: resume.md

  - wait: ~

  - block: ':email: Schedule Interview?'
    prompt: 'Fill out the details'
    fields:
      - text: 'Name'
        key: 'name'
        hint: 'How should I address you?'
        required: true
      - text: 'Email'
        key: 'email'
        hint: 'Your email address that I can reply to'
        format: '^[^\s@]+@[^\s@]+\.[^\s@]+$'
        required: true
      - text: 'Message'
        key: 'message'
        required: true

  - label: ':rocket: Schedule Interview'
    command: |
      export REPLY_TO_EMAIL=$(buildkite-agent meta-data get email)
      export REPLY_TO_NAME=$(buildkite-agent meta-data get name)
      export BODY=$(buildkite-agent meta-data get message)
      ruby scripts/send_email.rb
    secrets:
      - SMTP_USER
      - SMTP_SECRET
    plugins:
      - docker#v5.13.0:
          image: 'ruby:3.4.8-alpine'
          mount-buildkite-agent: true
          volumes:
            - '.:/app'
          workdir: '/app'
          environment:
            - 'SMTP_USER'
            - 'SMTP_SECRET'
            - 'SMTP_HOST=smtp.mail.me.com'
            - 'SMTP_PORT=587'
            - 'FROM_EMAIL=dyego@dyegocosta.com'
            - 'TO_EMAIL=dyego@dyegocosta.com'
            - 'SUBJECT=Interview Request From Buildkite'
