steps:
  - group: ':baby::skin-tone-5: Early Education'
    steps:
      - label: 'High School'
        key: 'high-school'
        command: scripts/study.sh
      - label: 'Microsoft Students To Business'
        command: scripts/study.sh
      - label: 'Certified Computer Systems Analyst'
        command: scripts/study.sh

  - wait: ~

  - group: ':adult::skin-tone-5: College Years'
    steps:
      - label: 'Information Technology for Business'
        command: scripts/study.sh
        depends_on: 'high-school'
      - label: 'Software Engineer at MCOM'
        key: 'mcom'
        command: scripts/work.sh
        artifact_paths: ./experience.md

  - wait: ~

  - group: ':male_mage::skin-tone-5: Professional Experience'
    steps:
      - label: 'Software Engineer at Lambda3'
        key: 'lambda3'
        depends_on: 'mcom'
        command: scripts/work.sh
        artifact_paths: ./experience.md
      - label: 'Software Engineer at Springboard Retail'
        key: 'springboard-retail'
        depends_on: 'lambda3'
        command: scripts/work.sh
        artifact_paths: ./experience.md
      - label: 'Software Engineer at Heartland (A Global Payments Company)'
        key: 'heartland'
        depends_on: 'springboard-retail'
        command: scripts/work.sh
        artifact_paths: ./experience.md
      - label: 'Software Engineer at BiggerPockets'
        key: 'biggerpockets'
        depends_on: 'heartland'
        command: scripts/work.sh
        artifact_paths: ./experience.md
        soft_fail: true
      - label: 'Software Engineer at Buildkite'
        depends_on: biggerpockets
        command: scripts/work.sh

  - wait: ~

  - block: ':email: Schedule Interview?'
    prompt: 'Fill out the details'
    fields:
      - text: 'Name'
        key: 'name'
        required: true
      - text: 'Email'
        key: 'email'
        format: '^[^\s@]+@[^\s@]+\.[^\s@]+$'
        required: true
      - text: 'Message'
        key: 'message'
        required: true

  - label: ':rocket: Schedule Interview'
    command: scripts/send_email.rb
    plugins:
      - docker#v5.13.0:
          image: 'ruby:3.4.8-alpine'
          volumes:
            - '.:/app'
          workdir: '/app'
          environment:
            - 'REPLY_TO_EMAIL'
            - 'REPLY_TO_NAME'
            - 'BODY'
            - 'SMTP_USER'
            - 'SMTP_SECRET'
            - 'SMTP_HOST=smtp.mail.me.com'
            - 'SMTP_PORT=587'
            - 'FROM=dyego@dyegocosta.com'
            - 'TO=dyego@dyegocosta.com'
            - 'SUBJECT=Interview Request From Buildkite'
    env:
      REPLY_TO_EMAIL: '{{ buildkite.meta.email }}'
      REPLY_TO_NAME: '{{ buildkite.meta.name }}'
      BODY: '{{ buildkite.meta.message }}'
